use ivi;
update persons  set biography = "У Джосса Уидона есть 2 старших брата Сэмуель и Меттью, а так же 2 младших брата Джед и Зак." where id = 178; 
 update persons  set biography = "На протяжении многих лет Дауни-младший практикует боевой стиль ушу Вин-Чунь." where id = 10096; 
 update persons  set biography = "Крис Эванс - вегетарианец." where id = 49627; 
 update persons  set biography = "Марк Руффало - вегетарианец." where id = 10467; 
 update persons  set biography = "18 марта 2014 года у Криса и Эльзы родились двойняшки." where id = 1300401; 
 update persons  set biography = "4 сентября 2014 года Йоханссон родила от Ромена Дориака (Romain Dauriac) девочку, которая получила имя Роуз." where id = 3903; 
 update persons  set biography = "Долгое время всерьёз занимался отделкой домов для их последующей перепродажи. Дела шли настолько хорошо, что Джереми продолжал больше зарабатывать на недвижимости, чем на съемочной площадке вплоть до 2008 года." where id = 5468; 
 update persons  set biography = "У Тома паническая боязнь акул - селахофобия." where id = 553143; 
 update persons  set biography = "С детства и по сей день борется с заиканием. В итоге, научился «имитировать» тех кто не заикается, используя аффирмацию - слово «motherfucker»." where id = 7164; 
 update persons  set biography = "В 2015 году Коби рассказала, что у неё был выявлен рак яичников во время съемок третьего сезона «Как я встретил вашу маму»." where id = 554916; 
 update persons  set biography = "Полное имя — Стеллан Йон Скарсгард (Stellan John Skarsgård)." where id = 11661; 
 update persons  set biography = "В 1999 и 2000 годах Пэлтроу стала объектом навязчивого преследования человеком по имени Данте Майкл (Dante Michael Siou), который, по сведениям некоторых источников, якобы посылал актрисе от пяти до десяти посылок в неделю, от признаний в любви, цветов и сладостей до религиозных памфлетов и непристойностей. Актриса получала десятки писем еженедельно и более 1200 электронных писем в общей сложности. За этим последовали угроза сексуального характера и неоднократные появления Данте в доме Пэлтроу. Преследования продолжались несмотря на полученное Данте предупреждение от ФБР, после чего он был приговорён к нескольким годам лечения в психиатрической лечебнице." where id = 3181; 
 update persons  set biography = "31 мая 2011 родилась дочь Агнес Ларк." where id = 14363; 
 update persons  set biography = "У Алексиса и его жены Элисон Хэннигэн две дочери: Сатьяна Мэри Денисоф (24.03.2009 г.р.) и Кива Джейн Денисоф (23.05.2012 г.р.)." where id = 25971; 
 update persons  set biography = "Умер в своём доме от сердечного приступа, до этого страдая полгода раком поджелудочной железы." where id = 987; 
 update persons  set biography = "У Дженни Агаттер есть сын от брака с Йоханом Тэмом - Джонатан Тэм (25.12.90)." where id = 49694; 
 update persons  set biography = "Во время Второй Мировой служил во флоте. Участвовал в битве за Окинаву." where id = 22209; 
 update persons  set biography = "Полное имя - Эшли Сьюзен Джонсон." where id = 50753; 
 update persons  set biography = "Окончил среднюю школу Amador High School в Саттер Крик (Калифорния), в 2002 году - Калифорнийский университет в Беркли со степенью бакалавра искусств в области английского языка и в 2005 году - аспирантуру в Школе искусств Тиш частного Нью-Йоркского университета со степенью магистра искусств." where id = 1107215; 
 update persons  set biography = "В возрасте 17 лет Стэн Ли (тогда ещё Стэнли Либер) устроился помощником художника в Marvel. До того, как студия Disney купила Marvel, Стэн Ли был президентом и председателем совета директоров." where id = 8242; 
 update persons  set biography = "08.09.2006 года, выступая на ежегодном съезде Национальной ассоциации журналистов - геев и лесбиянок США в Майами (Флорида), Томас Робертс совершил каминг-аут, публично сообщив о своей гомосексуальной ориентации." where id = 2428196; 
 update persons  set biography = "Полное имя - Jonathan Kolia Favreau." where id = 9559; 
 update persons  set biography = "Скончался от онкологического заболевания." where id = 290228; 
 update persons  set biography = "Патрон Эдинбургского международного кинофестиваля. Почетный член Эдинбургского колледжа искусств." where id = 610724; 
 update persons  set biography = "Должен был написать музыку для фильма «Пираты Карибского моря: Проклятие Черной жемчужины», но был заменен Клаусом Бадельтом." where id = 553348; 
 update persons  set biography = "Фабриция владеет пятью языками: английским, итальянским, немецким, французким, и испанским." where id = 28550; 
 update persons  set biography = "Полное имя - Пьер-Мари Денис Ардити (Pierre-Marie Denis Arditi)." where id = 19465; 
 update persons  set biography = "Его родители - алжирские евреи." where id = 41762; 
 update persons  set biography = "Его мама - испанка, родилась в Испании, городе Бильбао, эмигрировала в СССР после начала в Испании Гражданской войны, его отец - родился и вырос в Литве." where id = 307567; 
 update persons  set biography = "Во время Первой мировой войны служил пилотом." where id = 179334; 
 update persons  set biography = "Погиб в автокатастрофе." where id = 389445; 
 update persons  set biography = "У Алана Армстронга есть сын - Джо Армстронг." where id = 12083; 
 update persons  set biography = "Его отец - ветеран сцены и актёр кино - Алун Армстронг." where id = 560342; 
 update persons  set biography = "Учился в начальной школе Хеингтон (Heighington CE Primary School), а после её окончания - в общеобразовательной школе Вудэм (Woodham Comprehensive School). Обе расположены в городе Ньютон Эйклиф, графство Дарем." where id = 50871; 
 update persons  set biography = "Настоящее имя - Дональд Роберт Смит (Donald Robert Smith)." where id = 210064; 
 update persons  set biography = "Умерла от сердечного приступа." where id = 209059; 
 update persons  set biography = "29 июня 2012 года у Джоша и его супруги Джессики родился сын — Ной Рев Маурер." where id = 10974; 
 update persons  set biography = "Коко умер от сердечной недостаточности." where id = 2240695; 
 update persons  set biography = "25 апреля 2007 года Касл-Хьюз родила дочь Фелисити-Эймор. Отцом её дочери является Брэдли Халл, которому был 21 год когда она родилась." where id = 40952; 
 update persons  set biography = "Полное имя - Ной Джордж Тейлор (Noah George Taylor)." where id = 7227; 
 update persons  set biography = "Умер от рака желудка в доме своей матери в Вальбеке, недалеко от Лейпцига, куда приехал за несколько дней до смерти. Похоронен там же." where id = 44389; 
 update persons  set biography = "У Адрианы и Вольфганга Бёмера есть сын - актёр Аарон Альтарас." where id = 383822; 
 update persons  set biography = "У Кати Риманн есть дочь от фактического брака с Питером Заттманом - Паула Эмбер Роми Риманн (род.03.08.1993)." where id = 83523; 
 update persons  set biography = "У Ника есть младшая сестра Саманта Хейман (Samantha Heyman)." where id = 1091662; 
 update persons  set biography = "Имеет двух братьев и двух сестер - Алексис Аркетт, Дэвид Аркетт, Патриция Аркетт, Розанна Аркетт, которые также стали актерами ." where id = 8460; 
 update persons  set biography = "Умер от сердечного приступа." where id = 25003; 
 update persons  set biography = "У актера есть брат-близнец Аарон Эшмор." where id = 8235; 
 update persons  set biography = "Полное имя - Жан Марсель Бретонньер (Jean Marcel Bretonnière)." where id = 204647; 
 update persons  set biography = "Настоящее имя - Кристиана Элизабет Жанн Мари Пеллетера де Борд (Christiane Elisabeth Jeanne Marie Pelleterat de Borde)." where id = 156295; 
 update persons  set biography = "Его внучки - Эмманюэль и Матильда - актрисы." where id = 317343; 
 update persons  set biography = "Настоящее имя - Эдвард Константиновский (Edward Constantinowsky)." where id = 125401; 
 update persons  set biography = "Настоящее имя - Жак Поль Жюль Мария Давид (Jacques Paul Jules Marie David)." where id = 107423; 
 update persons  set biography = "Настоящее имя - Мари Жоржетт Дюбуа (Marie Georgette Dubois)." where id = 159115; 
 update persons  set biography = "Настоящее имя - Морис Гёртни (Maurice Gurtner)." where id = 359533; 
 update persons  set biography = "Настоящее имя - Симоне Исабелле Марчанд (Simone Isabelle Marchand)." where id = 347202; 
 update persons  set biography = "Полное имя - Жорж Морис ван Бевер (Georges Maurice van Bever)." where id = 205462; 
 update persons  set biography = "Полное имя - Фернан Мариус Шарпен (Fernand Marius Charpin)." where id = 503204; 
 update persons  set biography = "Полное имя - Тереза Жанн Лонго-Дорни (Thérèse Jeanne Longo-Dorni)." where id = 204946; 
 update persons  set biography = "Умер от сердечного приступа." where id = 270570; 
 update persons  set biography = "В 1980 году окончил ВГИК (мастерская Л.Косматова, Н.Василькова)." where id = 75880; 
 update persons  set biography = "Настоящее имя – Анна–Мария Массатани." where id = 181001; 
 update persons  set biography = "Проходил пробы на роль Гэндальфа к фильму «Властелин колец: Братство кольца» (2001), но роль получил Иэн МакКеллен*. Однако актер озвучил Гэндальфа в английской версии картины." where id = 87473; 
 update persons  set biography = "Умер от расслоения аорты." where id = 1959684; 
 update persons  set biography = "Причиной смерти артиста стал панкреатический рак." where id = 7114; 
 update persons  set biography = "Настоящее имя – Тьерри Кауфманн." where id = 15391; 
 update persons  set biography = "Кроме актерства Стефано активно занимается уличным дизайном, дизайном мебели и аксессуаров." where id = 34753; 
 update persons  set biography = "Полное имя - Ренато Алдо Россини Валенсуела (Renato Aldo Rossini Valenzuela)." where id = 1297566; 
 update persons  set biography = "Его дети - актёры Тесса Обержонуа (Tessa Auberjonois) и Реми Обержонуа (Remy Auberjonois)." where id = 7408; 
 update persons  set biography = "Дочь французского актёра Жан-Пьера Омон (1911-2001), который из-за своего происхождения был вынужден в 1940 году покинуть Париж." where id = 178292; 
 update persons  set biography = "Полное имя - Жан Мишель Роллен Рот Ле Жентиль (Jean Michel Rollin Roth Le Gentil)." where id = 385859; 
 update persons  set biography = "У Роз Райан есть сын от одного из двух её бывших мужей." where id = 75639; 
 update persons  set biography = "У Валерии Бруни-Тедески есть приёмная дочь от гражданского брака с Луи Гаррелем - Селин Гаррел (род.2008)." where id = 71765; 
 update persons  set biography = "Училась на театральных курсах Ф. Флориана, затем в Парижской консерватории у А. Витеза." where id = 60451; 
 update persons  set biography = "Ари Эльмалех - брат Гада Эльмалех." where id = 465633; 
 update persons  set biography = "Обучалась в Национальной консерватории драматического искусства и оперному пению в консерватории Aubervilliers (Conservatoire d’Aubervilliers)." where id = 1150993; 
 update persons  set biography = "Является дочерью актёра Рихарда Заммеля." where id = 1507568; 
 update persons  set biography = "Мать Сирила - немка, отец - француз." where id = 537681; 
 update persons  set biography = "Артур Жюньо - сын актера Жерара Жюньо и художника по костюмам Сесиль Маньян." where id = 247811; 
 update persons  set biography = "Санджай - младший брат актера Анила Капура и продюсера Бони Капура, сын кинопродюсера Суриндера Капура." where id = 255158; 
 update persons  set biography = "Её полное имя - Мамта Мукунд Кулкарни." where id = 243852; 
 update persons  set biography = "Родилась  в семье видных политических деятелей, её дед был премьер-министром Непала с 1959 по 1960 годы." where id = 226373; 
 update persons  set biography = "Его дочь - актриса Джухи Баббар, сын - Арья Баббар." where id = 228954; 
 update persons  set biography = "У него есть сестра-близнец - Шобха Кхоте." where id = 74059; 
 update persons  set biography = "У Смиты Патиль был сын от брака с Раджом Баббаром - Пратик Баббар (28.11.86)." where id = 156333; 
 update persons  set biography = "Некоторые фильм с его участием были завершены еще при жизни актера, но выпущены в прокат уже после смерти." where id = 115793; 
 update persons  set biography = "Является матерью Мегны Гулзар." where id = 228951; 
 update persons  set biography = "Его отец, Кевал Кришан Сиканд, был инженером-строителем и правительственным подрядчиком, его мама, Рамешвари. У Прана три брата и три сестры." where id = 289538; 
 update persons  set biography = "Настоящее имя - Гопал Беди (Gopal Bedi)." where id = 275985; 
 update persons  set biography = "Её отец - режиссёр Нанубхай Десаи (Nanubhai Desai)." where id = 256190; 
 update persons  set biography = "Его отец - известный бенгальский певец Апареш Лахири, мама - композитор и певица Баншори Лахири." where id = 283369; 
 update persons  set biography = "Является отцом Карана Джохара." where id = 102691; 
 update persons  set biography = "Сын, Каран Джохар, также стал режиссёром, сценаристом и продюсером." where id = 486438; 
 update persons  set biography = "Его братья - режиссёр и сценарист Яш Чопра и оператор - Дхарам Чопра. Сын - продюссер и режиссёр - Рави Чопра. Также ест две дочери." where id = 303195; 
 update persons  set biography = "Её сын Сикандер Кхер тоже стал актером." where id = 297861; 
 update persons  set biography = "Умер от сердечного приступа." where id = 245406; 
 update persons  set biography = "У Ритика Рошана шесть пальцев на правой руке." where id = 19354; 
 update persons  set biography = "Полное имя - Нутан Бехл." where id = 292620; 
 update persons  set biography = "У Рати Агнихотри есть сын от брака с Анилом Вирвани - Тануж Вирвани (род.1987)." where id = 224216; 
 update persons  set biography = "Отец актера Вивека Обероя." where id = 156331; 
 update persons  set biography = "Полное имя - Rajesh Roshan lal Nagrath." where id = 223954; 
 update persons  set biography = "Бабушка Шахида Капура." where id = 43801; 
 update persons  set biography = "Полное имя - Джагдип Сайед Иштиак Ахмед Джаффри." where id = 261495; 
 update persons  set biography = "Её старшая сестра - актриса Димпл Кападия (Dimple Kapadia)." where id = 310340; 
 update persons  set biography = "Актёр Имран Кхан приходится ему внуком." where id = 324052; 
 update persons  set biography = "Хелен является мачехой актёра Салмана Кхана." where id = 238251; 
 update persons  set biography = "Дядя Рандхира Капура, Риши Капура, Раджива Капура и Карана Капура." where id = 243859; 
 update persons  set biography = "Актёры Рахул Кханна и Акшая Кханна - сыновья Винода от первого брака." where id = 236174; 
 update persons  set biography = "Его отец - актёр Мурад (Murad)." where id = 255167; 
 update persons  set biography = "Его настоящее имя - Говинда Арун Ахуджа." where id = 228891; 
 update persons  set biography = "У Равины есть две приёмные дочери - 1984 года рождения и 1985 года рождения. Она удочерила их ещё до замужества." where id = 230108; 
 update persons  set biography = "Полное имя - Сатиш Равилал Шах (Satish Ravilal Shah)." where id = 229832; 
 update persons  set biography = "Полное имя - Химани Бхатт Шивпури (Himani Bhatt Shivpuri)." where id = 228897; 
 update persons  set biography = "Настоящее имя - Аджитеш Кумар Ирани." where id = 255153; 
 update persons  set biography = "Имя при рождении - Джон Пракаш Рао Джанумала (John Prakash Rao Janumala)." where id = 228872; 
 update persons  set biography = "Племянница Хемы Малини и Дхармендры." where id = 260151; 
 update persons  set biography = "Является братом Прити Сапру." where id = 249133; 
 update persons  set biography = "Настоящее имя - Фироз Кхан (Firoz Khan)." where id = 705192; 
 update persons  set biography = "Его сын, Навин Асрани (1969), является признанным стоматологом в Ахмадабаде." where id = 1105616; 
 update persons  set biography = "Погибла, выпав из окна 5-го этажа своей квартиры." where id = 280086; 
 update persons  set biography = "Есть брат-близнец, который старше Рахула на 26 минут." where id = 258474; 
 update persons  set biography = "Мать Каджол и Танишы Мукхерджи." where id = 256196; 
 update persons  set biography = "Его отец - актёр Раджендра Кумар." where id = 236043; 
 update persons  set biography = "Актёр ушёл из жизни в 7 часов 30 минут 12 января 2005 года в госпитале города Мумбаи (Индия) в результате кровоизлияния в мозг после перенесённой операции." where id = 156741; 
 update persons  set biography = "Умер от туберкулеза." where id = 315561; 
 update persons  set biography = "Её отец - индус, а мама - мусульманка." where id = 272921; 
 update persons  set biography = "Настояшее имя - Ума Кашьяп (Uma Kashyap)." where id = 322089; 
 update persons  set biography = "У Йогиты Бали есть шестеро детей - четыре сына и две дочери (четверо из них от второго брака с Митхуном Чакраборти)." where id = 317605; 
 update persons  set biography = "Санджив Кумар скончался в 1985 году в возрасте 47 лет в результате обширного инфаркта. По иронии судьбы, Санджив играл много пожилых ролей, а умер, не дожив и до пятидесяти." where id = 293594; 
 update persons  set biography = "Является старшим братом Амриша и Мадана Пури." where id = 594409; 
 update persons  set biography = "Актёр умер от рака в бомбейской больнице." where id = 334450; 
 update persons  set biography = "Его сын Фардин Кхан - известный актер." where id = 283580; 
 update persons  set biography = "Настоящее имя - Мумтаз Бану." where id = 326878; 
 update persons  set biography = "Его сын - актёр Киран Кумар (Kiran Kumar)." where id = 286811; 
 update persons  set biography = "Имя при рождении - Шашикала Джавалкар (Shashikala Jawalkar)." where id = 315555; 
 update persons  set biography = "Oтeц актрисы Джульeтт Льюис." where id = 7097; 
 update persons  set biography = "Настоящее имя - Майкл Синнотт (Michael Sinnott)." where id = 197844; 
 update persons  set biography = "Училась в Лицее Анри IV и Сорбонне, где получила философское образование." where id = 18081; 
 update persons  set biography = "Родители - сценарист и режиссер Паскаль Боницер и режиссер Софи Фийер." where id = 91486; 
 update persons  set biography = "Окончил музыкальное училище им. Ипполитова-Иванова." where id = 251140; 
 update persons  set biography = "Настоящее имя - Харуо Янагихара (Haruo Yanagihara)." where id = 62001; 
 update persons  set biography = "Ёдзи Ямада закончил Токийский университет в 1954 году и в том же году начал работать на студии Shochiku ассистентом режиссера." where id = 321402; 
 update persons  set biography = "Учился в Токийском университете искусств по классу композиции, однако не закончил его." where id = 553011; 
 update persons  set biography = "У Трине Дюрхольм есть сын от брака с режисером и хореографом Никласом Бендиксоном." where id = 45776; 
 update persons  set biography = "Настоящее имя - Kumudlal Kunjilal Ganguly." where id = 300547; 
 update persons  set biography = "Его дедушка - известный актёр Притвирадж Капур, два дяди также актёры - Шамми Капур и Шаши Капур." where id = 226194; 
 update persons  set biography = "Его отец  Дари Сингх, министр связи Индии, в прошлом знаменитый на всю Азию чемпион по армрестлингу, кинопродюсер и один из основателей Болливуда." where id = 1460606; 
 update persons  set biography = "Настоящее имя - Кертис Фишер (Curtis Fisher)." where id = 544147; 
 update persons  set biography = "Отец Эндрю - русский, мать - венесуэлка." where id = 9444; 
 update persons  set biography = "Американский дуэт, работающий в жанрах дарк-эмбиент и этереал-вэйв. Основан в 1994 году в городе Шардон (предместье Кливленда, штат Огайо)." where id = 1152198; 
 update persons  set biography = "Причиной смерти стало падение и травма головы; у актера были проблемы с ногами, он передвигался в инвалидном кресле." where id = 1865; 
 update persons  set biography = "В 1941 г. окончил актерский факультет Театрального училища имени Щепкина." where id = 193831; 
 update persons  set biography = "Закончил актерский факультет Ленинградского государственного театрального института им. А. Островского." where id = 281087; 
 update persons  set biography = "Старший брат артиста Романа Мадянова." where id = 327429; 
 update persons  set biography = "Полное имя - Толбузина Зоя Николаевна." where id = 315849; 
 update persons  set biography = "Сын Лилии Алёшниковой и Якова Сегелея - кинооператор Александр Алёшников." where id = 310467; 
 update persons  set biography = "Заслуженный артист РФ (1996)." where id = 217786; 
 update persons  set biography = "У Леонида есть сын Егор (2002 г.р.) от гражданского брака с актрисой Ольгой Головановой." where id = 290494; 
 update persons  set biography = "Окончила актёрский факультет ВГИКа в 1972 году." where id = 313388; 
 update persons  set biography = "Похоронен на 25-м участке Перепечинского кладбища рядом с могилой жены Нины Никольской (1918-2003)." where id = 269699; 
 update persons  set biography = "Заслуженная артистка РСФСР (1983)." where id = 196181; 
 update persons  set biography = "Заслуженная артистка РСФСР (1958)." where id = 221278; 
 update persons  set biography = "Пётр Евгеньевич Катаев является сыном советского писателя Евгения Петрова (Евгения Петровича Катаева)." where id = 313275; 
 update persons  set biography = "Является матерью актера Хавьера Бардема." where id = 80839; 
 update persons  set biography = "В 1991 году вместе со своей группой Гарри Бардин основал собственную студию «Стайер»." where id = 174295; 
 update persons  set biography = "Иосиф Яковлевич Боярский в 1963-1978 годах был директором кукольного объединения «Союзмультфильма»." where id = 1152215; 
 update persons  set biography = "В 1936 окончил художественный техникум ОГИЗа, затем – Институт повышения квалификации художников-иллюстраторов." where id = 328771; 
 update persons  set biography = "Народный артист Российской Федерации (1996)." where id = 322243; 
 update persons  set biography = "Режиссер и мультипликатор умер во сне от инфаркта в ночь на 22 июля." where id = 313367; 
 update persons  set biography = "Всего у Дайан Лэдд было две дочери от первого брака с Брюсом Дерном - Дайан Элизабет Дерн (скончалась в 1.6-летнем возрасте от травм, полученных после падения в бассейн) и Лора Элизабет Дерн (известная актриса)." where id = 10784; 
 update persons  set biography = "Всего у Клорис Личмен было пятеро детей от брака  с Джорджом Инглундом, четыре сына и дочь -  Адам Инглунд (род.1954), Брайан Инглунд (род.1956-род.25.02.1986, умер от передозировки лекарств по лечению язвы), Джордж Х. Инглунд (род.1957), Морган Инглунд (род.1964) и Дина Инглунд (род.1967)." where id = 11760; 
 update persons  set biography = "В 2015 году Вэлу Килмеру был диагностирован рак горла." where id = 8516; 
 update persons  set biography = "Семья актёра имела российские, венгерские, чешские (с материнской стороны) и польские (с отцовской стороны) корни. Родители его отца, Луис и Ида Фальк, иммигрировали в США из Российской империи в начале 1890-х." where id = 8367; 
 update persons  set biography = "Ханна училась в школе Роки Маунтин в Карбондэйле (Колорадо). Закончила её в 2002 году." where id = 24763; 
 update persons  set biography = "Мать Лин родилась в России." where id = 2087; 
 update persons  set biography = "Бу Бу - сын актёра Нильса Аллена Стюарта." where id = 547063; 
 update persons  set biography = "У Марии Барранко есть дочь от гражданского брака с Иманолем Урибе - Андреа Урибе (род.1993)." where id = 3779; 
 update persons  set biography = "Пьер Ренуар - сын французского художника-импрессиониста Пьера-Огюста Ренуара." where id = 674153; 
 update persons  set biography = "Полное имя - Жан-Луи Бернар Барро (Jean-Louis Bernard Barrault)." where id = 163979; 
 update persons  set biography = "Настоящее имя - Жак Генри Нюсбомэ (Jacques Henri Nusbaumer)." where id = 354763; 
 update persons  set biography = "Полное имя - Жан Луи Брошар (Jean Louis Brochard)." where id = 204945; 
 update persons  set biography = "Активная участница французского Сопротивления в годы Второй мировой войны. В 1945 награждена Шарлем де Голлем Военным крестом." where id = 154995; 
 update persons  set biography = "Полное имя - Жак Габриэль Дюфийо (Jacques Gabriel Dufilho)." where id = 173699; 
 update persons  set biography = "Полное имя - Марк Анри Ноэль Аллегре (Marc Henri Noël Allégret)." where id = 204624; 
 update persons  set biography = "В 1947 Шведская академия присудила Жиду Нобелевскую премию «за глубокие и художественно значимые произведения, в которых человеческие проблемы представлены с бесстрашной любовью к истине и глубокой психологической проницательностью»." where id = 707494; 
 update persons  set biography = "Полное имя - Жан Марсель Дезайи (Jean Marcel Desailly)." where id = 168280; 
 update persons  set biography = "Жена в девичестве Николь Фуркад по желанию Жерара сменила имя на Анн." where id = 205480; 
 update persons  set biography = "Имеет украинское происхождение." where id = 351492; 
 update persons  set biography = "Умер от осложнений, связанных с сахарным диабетом." where id = 618615; 
 update persons  set biography = "Бывший участник группы Pink Floyd." where id = 164836; 
 update persons  set biography = "Умер от рака." where id = 612465; 
 update persons  set biography = "Ласки был похоронен на кладбище «Hollywood Forever», что рядом с «Paramount Studios» в Голливуде." where id = 208906; 
 update persons  set biography = "Основатель кинокомпании Paramount Pictures." where id = 218952; 
 update persons  set biography = "25 октября 1933 года Лилиан заперлась на кухне своего дома, включила газ, сунула голову в духовку и перерезала горло бритвой брата. Ее 14-летний сын, придя из школы домой, нашел ее предсмертную записку." where id = 221491; 
 update persons  set biography = "Настоящее имя - Фрэнк Томас Финей (Frank Thomas Feeney)." where id = 206559; 
 update persons  set biography = "Похоронен на родине в Палермо, на кладбище Санта Мария дель Ротоли." where id = 195831; 
 update persons  set biography = "Персонаж компьютерных игр Mass Effect 2 и Mass Effect 3 Миранда Лоусон получила от Ивонн Страховски внешность и голос." where id = 1117925; 
 update persons  set biography = "Является дочерью актрисы Ракхи Гулзар." where id = 600453; 
 update persons  set biography = "Его отец - сценарист Салим Кхан." where id = 236034; 
 update persons  set biography = "Настоящее имя - Джасджит Синх Шергилл (Jasjit Singh Shergill)." where id = 269533; 
 update persons  set biography = "Её отец - Шивиндер Сингх (Shivinder Singh), её мама - актриса Руксана Султана (Rukshana Sultana). Её дядя - писатель и сценарист Кушвант Сингх (Khushwant Singh). Её дед - сэр Шобха Сингх (Shobha Singh), был известным строителем в Индии." where id = 278616; 
 update persons  set biography = "Полное имя - Неха Прадип Дхупия." where id = 674159; 
 update persons  set biography = "Полное имя - Диа Мирза Хандрич (Dia Mirza Handrich)." where id = 230368; 
 update persons  set biography = "Родился в семье кашмирских брахманов." where id = 37288; 
 update persons  set biography = "Его отец - итальянец, а мама - индианка." where id = 230116; 
 update persons  set biography = "Её брат - оператор Баба Азми." where id = 73383; 
 update persons  set biography = "Является родственником афганского писателя Идрис Шаха." where id = 31595; 
 update persons  set biography = "Санджай - один из трех детей. У него есть две младшие сестры: Прийя и Намрата." where id = 19353; 
 update persons  set biography = "Имеет чёрный пояс по восточным единоборствам." where id = 230107; 
 update persons  set biography = "Анарудха Патель является внучкой Ашока Кумара." where id = 306741; 
 update persons  set biography = "Настоящее имя - Сампуран Сингх Калра (Sampooran Singh Kalra)." where id = 236095; 
 update persons  set biography = "Его отец Виру Девган (Veeru Devgan) - режиссер и каскадер. Его кузен Анил Девган - болливудский режиссер." where id = 230103; 
 update persons  set biography = "Бипаша свободно говорит на хинди, английском и бенгальском языках." where id = 228944; 
 update persons  set biography = "Химеш по происхождению - гуджаратец." where id = 228916; 
 update persons  set biography = "У Прити Джангиани есть сын (род.11.04.2011) от брака с Парвином Дабас." where id = 230104; 
 update persons  set biography = "Есть две сестры и один брат." where id = 37188; 
 update persons  set biography = "Настоящая фамилия - Гаркович." where id = 125050; 
 update persons  set biography = "Отец актрисы Тани Гарбарски." where id = 466102; 
 update persons  set biography = "У Марианны Фэйтфулл есть сын от первого брака с Джоном Данбаром - Николас Данбар (род.1965)." where id = 52284; 
 update persons  set biography = "Дочь актера Джека Гилпина." where id = 1152294; 
 update persons  set biography = "Является сводным братом актера Лива Шрайбера." where id = 49161; 
 update persons  set biography = "Полное имя - Мишель Луи Бон (Michel Louis Bosne)." where id = 156287; 
 update persons  set biography = "Полное имя - Мэтью Клейтон Лонг (Matthew Clayton Long)." where id = 596794; 
 update persons  set biography = "У него 3 младшие сестры - Дениз, Рене и Тедди." where id = 23417; 
 update persons  set biography = "Полное имя актера - Джеймс Пейдж Моррисон." where id = 1515; 
 update persons  set biography = "Новозеландская актриса и каскадер." where id = 10374; 
 update persons  set biography = "В 1969 году писателю была присуждена Нобелевская премия по литературе." where id = 13396; 
 update persons  set biography = "Полное имя - Марта Алисия Мартин." where id = 289744; 
 update persons  set biography = "Полное имя - Мария де Монтсеррат Вивиана Консепсьон Кабалье и Фолк." where id = 322643; 
 update persons  set biography = "У Андреа Ван Йенсен есть два сына - Харальд и Феликс." where id = 276428; 
 update persons  set biography = "Асси Дайан - сын Моше Дайана." where id = 150290; 
 update persons  set biography = "Марсель Карне родился в семье краснодеревщика, некоторое время работал страховым агентом." where id = 212858; 
 update persons  set biography = "Настоящее имя - Жан-Франсуа Анри Поль Буи (Jean-François Henri Paul Bouy)." where id = 190942; 
 update persons  set biography = "Полное имя - Люсьен Мария Паскаль Эжен Калламан (Lucien Marie Pascal Eugène Callamand)." where id = 200719; 
 update persons  set biography = "В декабре 2011 года у Роберта Де Ниро и его супруги Грейс Хайтауэр посредством суррогатного материнства родилась дочь Хелен Грэйс Хайтауэр Де Ниро (Helen Grace Hightower De Niro)." where id = 718; 
 update persons  set biography = "Настоящее имя — Маргарит Дюпю." where id = 185604; 
 update persons  set biography = "У Веры Бельтон был сын от первого брака с Жоэлем Ольме - Стефан Ольме (01.01.60-1990, разбился на мотоцикле в 30-ти летнем возрасте)." where id = 86539; 
 update persons  set biography = "Настоящее имя - Анни Люсьен Мари-Луиз Жаме (Annie Lucienne Marie-Louise Jamet)." where id = 182280; 
 update persons  set biography = "Полное имя - Пьер Андрэ Клементи (Pierre André Clémenti)." where id = 71841; 
 update persons  set biography = "Настоящее имя - Паскуале Загария (Pasquale Zagaria)." where id = 315506; 
 update persons  set biography = "Настоящее имя - Карла Дора." where id = 162487; 
 update persons  set biography = "Полное имя - Элиза Анжела Мария Чегани (Elisa Angela Maria Cegani)." where id = 204591; 
 update persons  set biography = "Состоит в гражданском браке с Деборой Фалабелла." where id = 12228; 
 update persons  set biography = "Полное имя - Juliana Couto Paes." where id = 857403; 
 update persons  set biography = "У Луаны Пиовани и Педро Скуби есть трое детей: сын - Дом Скуби (род.26.03.2012) и близнецы сын Бем и дочь Лиз (род. 2016)." where id = 383361; 
 update persons  set biography = "Отец актера Срджана Тодоровича и актрисы Даны Тодорович." where id = 96988; 
 update persons  set biography = "В начале 1990-х годов Эна, управлявшая автомобилем в городе Загреб (Хорватия), попала в тяжёлую автокатастрофу, повлёкшую за собой смерть одного из пассажиров. Она сама чудом выжила. Почти 10 лет спустя, 15 августа 2000 года в городе Брач (Хорватия), Бегович вновь попала в автокатастрофу. На этот раз чуда не произошло — 40-летняя актриса, новоиспечённая жена и мать полуторамесячной дочери Ланы скончалась от тяжёлой травмы головы. Женщина была похоронена на кладбище «Мирогой» в городе Загреб, городе где она впервые попала в автокатастрофу. После гибели женщины её вдовец, Иосиф Радельяк, жил в фактическом браке с актрисой Долорес Ламбаша (англ.)русск. (1981—2013), которая вырастила их дочь Лану. 13 лет спустя после гибели Бегович, 23 октября 2013 года, 32-летняя Ламбаша также погибла в автокатастрофе." where id = 132972; 
 update persons  set biography = "Умер от рака легких." where id = 73734; 
 update persons  set biography = "Родители Хэлли развелись, когда ей было 4 года, и она со своей старшей сестрой Хейди воспитывалась исключительно матерью." where id = 1179; 
 update persons  set biography = "В 9 лет Джастин прослушивался на роль Энакина Скайуокера в фильм «Звездные войны: Эпизод 1 - Скрытая угроза» (1999)." where id = 27254; 
 update persons  set biography = "Изучала английскую литературу в Кембриджском университете." where id = 12586; 
 update persons  set biography = "В 2003 году в возрасте 29 лет стал самым молодым актером, который когда-либо получал премию «Оскар» в номинации «Лучший актер»." where id = 2523; 
 update persons  set biography = "7 октября 2016 года родила девочку." where id = 419719; 
 update persons  set biography = "Мать Джин Макмиллан-Росс (урождённая Хауи) педагог и пианистка, отец - Иэн Бакстер Макмиллан, практикующий домашний врач и судебный хирург." where id = 24216; 
 update persons  set biography = "Помимо театра, кино и телевидения Максимилиан Шелл пишет и занимается живописью." where id = 3008; 
 update persons  set biography = "В восемь лет стал вегетарианцем по собственному желанию." where id = 1301970; 
 update persons  set biography = "У Энди русские и польские корни." where id = 14461; 
 update persons  set biography = "Полное имя - Nora Angela Zehetner." where id = 329; 
 update persons  set biography = "15 августа 2015 года у Джозефа Гордона-Левитта и его супруги Таши МакКоли родился сын." where id = 9867; 
 update persons  set biography = "Оба брата-близнеца Лукаса Хааса – Саймон (Simon Jakoway) и Николай (Nikolai Johannes) - также актеры и музыканты." where id = 24370; 
 update persons  set biography = "Комедия «Путешествие на Луну» (1902) — первый в истории кинематографа научно-фантастический фильм." where id = 415210; 
 update persons  set biography = "Cкончалась после продолжительной борьбы с раком молочной железы." where id = 226589; 
 update persons  set biography = "Отец — армянин — выходец из Российской империи, мать — француженка." where id = 16766; 
 update persons  set biography = "Его отец занимал пост конгрессмена в Огайо и председателя правления в издательской компании Браун. Его мама - дирижер, композитор и пианистка." where id = 20802; 
 update persons  set biography = "В честь Сары Бернар назван один из самых красивых и ароматных сортов гибридных пионов." where id = 365241; 
 update persons  set biography = "Полное имя - Генри Мария Родольф Баур (Henri Marie Rodolphe Baur)." where id = 251859; 
 update persons  set biography = "Настоящее имя - Жанна Луиз де Жарни (Jeanne Louise de Jarny)." where id = 370008; 
 update persons  set biography = "У Лили Дамита был сын от второго брака с Эрролом Флинн - Шон Лесли Флинн (род.31.05.1941-ум. предп. в июне 1971). Шон пропал без вести 6 апреля 1970 года, предположительно был убит похитителями в июне 1971 года, в 1984 году был заочно назван мёртвым." where id = 220850; 
 update persons  set biography = "Полное имя - Александр Жорж Пьер Гитри (Alexandre Georges Pierre Guitry)." where id = 92424; 
 update persons  set biography = "Полное имя - Пол Анри Капеллани (Paul Henri Capellani)." where id = 468734; 
 update persons  set biography = "Его отец - писатель Александр Дюма, его мать, Катрина Лабе, была простой парижской работницей." where id = 218682; 
 update persons  set biography = "Настоящее имя - Клемент Гратьюле (Clément Gratioulet)." where id = 900690; 
 update persons  set biography = "Полное имя - Шарль д' Отье де Рошфор (Charles d’Authier de Rochefort)." where id = 369384; 
 update persons  set biography = "Настоящее имя - Жан-Шарль Берниод (Jean-Charles Barniaud)." where id = 201634; 
 update persons  set biography = "У Колин Серро есть двое детей: сын Натанаэль Серро, чей отец неизвестен публике и дочь Мэделин Бессон от брака с Бенно Бессоном." where id = 130009; 
 update persons  set biography = "Полное имя - Пол Антуан Альфонс Бисцилия (Paul Antoine Alphonse Bisciglia)." where id = 177885; 
 update persons  set biography = "Настоящее имя - Поль Мариус Раймон Миньона (Paul Marius Raymond Mignonat)." where id = 183919; 
 update persons  set biography = "У Филиппо и его жены есть трое детей: Алессандро (2004 года рождения), Оливия (2010 года рождения) и Клаудио (2012 года рождения)." where id = 416098; 
 update persons  set biography = "Полное имя - Даниэль Ивонн Мари Антуанетт Дарьё (Danielle Yvonne Marie Antoinette Darrieux)." where id = 19583; 
 update persons  set biography = "Настоящее имя - Лаура Тромбетти (Laura Trombetti)." where id = 134218; 
 update persons  set biography = "Со своей будущей женой Энтони познакомился, когда ему было семь лет." where id = 32208; 
 update persons  set biography = "The Roots — американская хип-хоп-группа из Филадельфии." where id = 482442; 
 update persons  set biography = "Полное имя - Рагхумудри Шри Хари." where id = 684254; 
 update persons  set biography = "Полное имя - Даггубати Венкатеш (Daggubati Venkatesh)." where id = 504854; 
 update persons  set biography = "У Мишлин Прель есть дочь от брака с Уильямом Маршаллом - Энтони-Ли Кэролайн Джули Маршалл (29.11.51)." where id = 29486; 
 update persons  set biography = "Внук писателя Блеза Сандрара." where id = 243424; 
 update persons  set biography = "Полное имя - Роланд Люсьен Бланш (Roland Lucien Blanche)." where id = 92463; 
 update persons  set biography = "Немецкая актриса Марайке Карьер - родная сестра Матьё Карьера." where id = 115899; 
 update persons  set biography = "Похоронен на 9-м участке Преображенского кладбища." where id = 638222; 
 update persons  set biography = "Настоящее имя Анупа - Ануп Кумар Гангули." where id = 332808; 
 update persons  set biography = "Умер от рака легких." where id = 276000; 
 update persons  set biography = "Ришикеш Мукхерджи умер от хронической почечной недостаточности." where id = 331393; 
 update persons  set biography = "Его племянник - Аамир Кхан." where id = 547924; 
 update persons  set biography = "Его сын - актёр Зайед Кхан. Племянник актёр - Фардин Кхан." where id = 223953; 
 update persons  set biography = "Дядя Анджелины Джоли." where id = 169859; 
 update persons  set biography = "В 1985 году окончила Варшавскую высшую театральную школу." where id = 34769; 
 update persons  set biography = "У Беаты Тышкевич есть две дочери - Каролина Вайда (род.29.03.1967) от брака с Анджеем Вайда и Виктория Падлевски (род.04.10.1977) от брака с Яцеком Падлевски." where id = 238714; 
 update persons  set biography = "Скончался от онкологического заболевания." where id = 271311; 
 update persons  set biography = "Актер погиб, находясь в отпуске в местечке Влодава, в результате удара током. По информации польских СМИ, это произошло в подвале его летнего домика, где стояла вода." where id = 317127; 
 update persons  set biography = "У неё есть сын Людвиг. Её дочь, актриса и модель Барбара Космаль (1973—1993), трагически погибла в автомобильной катастрофе в Бжезины." where id = 251025; 
 update persons  set biography = "Умер от рака лёгких, похоронен на Старом кладбище в Лодзи." where id = 104718; 
 update persons  set biography = "Его супруга по професиии скрипачка. У них двое детей: сын Мачей Штур — актёр театра и кино, дочь Марианна Штур — художница." where id = 107126; 
 update persons  set biography = "Отец актера Лукаша Новицкого." where id = 25335; 
 update persons  set biography = "В 2013 году у Андреаса и его жены шведского дизайнера Николь Уилсон (Nicole Wilson) родился сын Ноэль (Noel)." where id = 382754; 
 update persons  set biography = "Профессор Высшей международной киношколы La Femis." where id = 702149; 
 update persons  set biography = "Полное имя - Филипп Теймур Хорсан (Philippe Taymour Khorsand)." where id = 15315; 
 update persons  set biography = "Сын актрисы - Мориц Бляйбтрой." where id = 44399; 
 update persons  set biography = "Полное имя - Brian Keith Bloom." where id = 10590; 
 update persons  set biography = "Предки Кима из России и Польши." where id = 90202; 
 update persons  set biography = "Является основателем и владельцем музыкального лейбла «StormVox»." where id = 6237; 
 update persons  set biography = "Актёр попал в Книгу рекордов Гиннеса за самую продолжительную кинокарьеру - возрасте 8 лет он дебютировал в фильме «Веселый крестьянин» (Der Fidel Bauer, 1908), а его последнее появление на экране состоялось в «Небе над Берлином» (Wings of Desire, 1988), когда ему было 88 лет." where id = 146291; 
 update persons  set biography = "Полное имя - Генрих Георг Людвиг Энгельманн (Heinrich Georg Ludwig Engelmann)." where id = 189894; 
 update persons  set biography = "У Оливии Бонами есть сын от гражданского брака с Ромэном Дурисом - Луиджи Дурис (10.02.09)." where id = 47407; 
 update persons  set biography = "Полное имя - Джордж Ховард Хессеман (George Howard Hesseman)." where id = 38570; 
 update persons  set biography = "Гийом - старший брат актрисы Жюли Депардье." where id = 60417; 
 update persons  set biography = "Ребенком жил с отцом по месту его работы в Колумбии." where id = 17648; 
 update persons  set biography = "Был вторым ребёнком в семье. Имел старшего брата (умер в младенчестве), трёх младших сестёр и младшего брата." where id = 72197; 
 update persons  set biography = "Полное имя - Джино Луиджи Черви (Gino Luigi Cervi)." where id = 25000; 
 update persons  set biography = "Родольфо был третьим сыном Гуччо Гуччи - производителя модной одежды и основателя одноимённой фирмы. После ряда неудачных ролей оставил кинематограф и ушёл в семейный бизнес." where id = 358972; 
 update persons  set biography = "Сын режиссёра Лассе Халльстрёма." where id = 944478; 
 update persons  set biography = "Хотя устоявшимся вариантом произношения фамилии Дика является «Chay-nee» (Чей-ни), правильный вариант - «Chee-nee» (Чи-ни)." where id = 41249; 
 update persons  set biography = "Имя при рождении - Лесли Линч Кинг, но в раннем детстве после развода родителей переименован в честь отчима и получил его фамилию." where id = 51038; 
 update persons  set biography = "Брат актера Глина Хьюстона." where id = 166374; 
 update persons  set biography = "Ферди - отец актрисы Белинды Мэйн." where id = 112479; 
 update persons  set biography = "Полное имя - Рональд Джордж Стивенс (Ronald George Stevens)." where id = 68548; 
 update persons  set biography = "Полное имя - Дора Франка Дуранти (Dora Franca Duranti)." where id = 326603; 
 update persons  set biography = "Его отец - продюсер Раймонд Бордери (Raymond Borderie)." where id = 430419; 
 update persons  set biography = "Настоящая фамилия - Гимен." where id = 186593; 
 update persons  set biography = "Полное имя - Ги Анри Делорм (Guy Henri Delorme)." where id = 173818; 
 update persons  set biography = "Полное имя - Юбер Луи Мария Дешамп (Hubert Louis Marie Deschamps)." where id = 183891; 
 update persons  set biography = "Актриса покончила с собой в возрасте 37 лет, после того, как стала жертвой жестокого изнасилования." where id = 181928; 
 update persons  set biography = "Настоящее имя - Эмиль Гастон Морис Бийре (Emile Gaston Maurice Billerey)." where id = 39842; 
 update persons  set biography = "Отец был итальянским евреем, мать — француженка из провинции Бретань." where id = 51697; 
 update persons  set biography = "Умерла от рака лёгких." where id = 69005; 
 update persons  set biography = "У Арлетт Саллес есть два сына от первого брака с Люсио Мауро - Александр Мауро (род.1959) и Гилберто Мауро (род.1969)." where id = 471213; 
 update persons  set biography = "Полное имя - Maria Natália Ferreira do Vale." where id = 662206; 
 update persons  set biography = "У Ингрид Гимараеш есть дочь от гражданского брака  с Рене Мачадо - Клара Мачадо (род.09.09.2009)." where id = 551061; 
 update persons  set biography = "Мать актера и режиссёра Роберту Бонтемпу." where id = 13810; 
 update persons  set biography = "Полное имя - Мауро Муньис де Уркиса (Mauro Muñiz de Urquiza)." where id = 138251; 
 update persons  set biography = "Изучала драму в Высшей национальной консерватории драматического искусства в Париже." where id = 565122; 
 update persons  set biography = "Полное имя - Мишель Франсуа Пьер Буке (Michel François Pierre Bouquet)." where id = 115159; 
 update persons  set biography = "За государственную измену приговорён к смертной казни через расстрел. В утро приведения приговора в исполнение, 15 октября 1945 года, Лаваль пытался покончить с собой, выпив яд (цианистый калий), но это было вовремя замечено, ему сделали несколько промываний желудка. После того, как Лаваль пришёл в сознание, он был расстрелян." where id = 115191; 
 update persons  set biography = "Похоронен в Валлорисе на Старом кладбище." where id = 58800; 
 update persons  set biography = "У Рауля и его бывшей жены - Кьяры Джордано (Chiara Giordano) трое детей: сыновья Алессандро Леон (Alessandro Leon) и Франческо (Francesco) и дочь Софи (Sophia)." where id = 34381; 
 update persons  set biography = "Кира Найтли его младшая дочь. Есть старший сын Калеб 1979 года рождения." where id = 78013; 
 update persons  set biography = "Актёр, сыгравший роль Курильщика в сериале «Секретные материалы», не курит и увлекается водными лыжами." where id = 3761; 
 update persons  set biography = "Настоящая имя - Ана Рита Пинту Мартинш (Ana Rita Pinto Martins)." where id = 258968; 
 update persons  set biography = "Лауреат Нобелевской премии мира 1971 года." where id = 2909; 
 update persons  set biography = "Настоящее имя - Клод Пьер Эспинас (Claude Pierre Espinasse)." where id = 19469; 
 update persons  set biography = "Его сын - актёр и музыкант Сэм Вудворд (Sam Woodward)." where id = 39774; 
 update persons  set biography = "Погиб в автокатастрофе." where id = 377520; 
 update persons  set biography = "Умер после двух лет борьбы с раком толстой кишки." where id = 101206; 
 update persons  set biography = "Его дочь, Дана Гомолова, стала актрисой и певицей." where id = 375796; 
 update persons  set biography = "У него есть старший брат, Аарон Эмбри (музыкальный продюсер и музыкант) и младшая сестра Кейша, которая является актрисой." where id = 11804; 
 update persons  set biography = "Полное имя - Жан-Клод Марсель Бриали (Jean-Claude Marcel Brialy)." where id = 3955; 
 update persons  set biography = "У Миу-Миу есть дочь Жанна Эрри от Жюльена Клерка. А также есть еще одна дочь Анжель от Патрика Девэра." where id = 83145; 
 update persons  set biography = "Внучка Чарли Чаплина." where id = 66989; 
 update persons  set biography = "Его дядя Серж Хароше в 2012 году стал лауреатом Нобелевской премии по физике." where id = 971293; 
 update persons  set biography = "Полное имя - Саймон Максвелл Хелберг." where id = 26550; 
 update persons  set biography = "В 2012 году женился на 29-летней балерине Куин Ландберг." where id = 44646; 
 update persons  set biography = "У Жаслин Таун есть дочь от брака с Саймоном Хелбергом - Эделин Хелберг (род.08.05.2012)." where id = 388714; 
 update persons  set biography = "Полное имя - Мануэль Александр Абарка (Manuel Alexandre Abarca)." where id = 282424; 
 update persons  set biography = "В 1995 году окончил факультет психологии Московского государственного университета, после чего занимался переводческой деятельностью." where id = 224611; 
 update persons  set biography = "Учился в Саратовском театральном училище, затем прошёл срочную службу на военно-морском флоте, работал актёром в Саратовском ТЮЗе, учился у Петра Фоменко в РАТИ, выпустился в 2001 году." where id = 1077031; 
 update persons  set biography = "Окончил Театрально-художественный институт в Ташкенте (1950), затем Школу-студию МХАТ (1955)." where id = 261544; 
 update persons  set biography = "С 2005 по 2006 актриса областного ТЮЗа (г. Царицыно)." where id = 1152723; 
 update persons  set biography = "В 1990 году окончил ЛГИТМиК (курс Аркадия Кацмана и Вениамина Фильштинского)." where id = 51601; 
 update persons  set biography = "1993 - 1996 - актриса Малого драматического театра - Театра Европы." where id = 1418939; 
 update persons  set biography = "Окончил Воронежский государственный театральный институт в 1998 году." where id = 554147; 
 update persons  set biography = "В 2001 году, сразу по окончании СПбГАТИ, был принят в труппу Театра на Литейном." where id = 1418941; 
 update persons  set biography = "Играл на сцене Тверского академического театра драмы в спектаклях «Чайка», «Обрыв», «Вишневом саде», «Волках и овцах» (на большой сцене)." where id = 1399039; 
 update persons  set biography = "С 2013 по 2016 год – актриса мастерской Клима, ЦДиР." where id = 1418945; 
 update persons  set biography = "У Сергея есть младший брат, Иван. Мама Сергея - хореограф." where id = 1418949; 
 update persons  set biography = "Заслуженная артистка России (1999)." where id = 251209; 
 update persons  set biography = "Лауреат Премии петербургской критики (1994, за роль Сережи Воробьева в спектакле Александра Галибина «Ла-фюнф ин дер люфт»)." where id = 231204; 
 update persons  set biography = "Сын Евланова его полный тезка - Евланов Михаил Михайлович." where id = 1600601; 
 update persons  set biography = "С 1994 по 2001 год - актер Саратовского ТЮЗа." where id = 1620799; 
 update persons  set biography = "В 1997 году окончил экономический факультет Московского Университета пищевых производств." where id = 555304; 
 update persons  set biography = "В 2002 году окончил операторский факультет ВГИКа." where id = 231244; 
 update persons  set biography = "В деревне Хауорт, в Западном Йоркшире, на родине сестер Бронте находится музей в их честь." where id = 86282; 
 update persons  set biography = "Сын, Габриэль Брук, погиб в автокатастрофе 14 июня 2004 года в возрасте 29 лет." where id = 89029; 
 update persons  set biography = "Эрик дель Кастильо родился в семье пожарного и сельской учительницы. Его отец происходил из знатной испанской семьи Толедо." where id = 197449; 
 update persons  set biography = "Полное имя -- Кайл Стивен Галлнер." where id = 34884; 
 update persons  set biography = "У Вирджинии Мэдсен есть сын от фактического брака с Антонио Сабато-младшим - Джек Антонио Сабато (род.06.08.1994)." where id = 4589; 
 update persons  set biography = "Училась в Американской Академии Драматического Искусства в Лос-Анджелесе." where id = 731114; 
 update persons  set biography = "Элиас Котеас - левша." where id = 9332; 
 update persons  set biography = "Полное имя — Тайсон Вуд." where id = 582283; 
 update persons  set biography = "Заслуженный артист России." where id = 231213; 
 update persons  set biography = "Полное имя - Ричард Семлер Бартелмесс (Richard Semler Barthelmess)." where id = 200646; 
 update persons  set biography = "У Мелани Браун есть трое дочерей: Феникс Чи Гюльзар (19.02.99) от первого брака с Джимми Гюльзаром, Энджел Айрис Мёрфи-Браун (03.04.07) от гражданского брака с Эдди Мёрфи и Мэдисон Браун-Белафонте (01.09.11) от второго брака со Стефенем Белафонте." where id = 28624; 
 update persons  set biography = "Полное имя - Чарльз Альберт Браунинг (Charles Albert Browning)." where id = 195002; 
 update persons  set biography = "Его старший брат - актёр Цезары Пазура (Cezary Pazura)." where id = 397609; 
 update persons  set biography = "Отец актеров Эмилиана Каминского (Emilian Kaminski, род.10.07.1952) и Дороты Каминской (Dorota Kaminska, род.07.06.1955)." where id = 273581; 
 update persons  set biography = "Его младший брат - актёр Радослав Пазура (Radoslaw Pazura)." where id = 107131; 
 update persons  set biography = "Сын Яна Махульского и Халины Махульской." where id = 294766; 
 update persons  set biography = "В 2009 году Кросс начал трехгодичный курс обучения в Лондонской академии музыкального и драматического искусства (LAMDA), надеясь улучшить своё актёрское мастерство и разговорный английский язык. Однако, Давид бросил обучение в конце того же года и сконцентрировался на съёмках в кино." where id = 459452; 
 update persons  set biography = "С 2010 года Брюль находится в отношениях с психологом Фелиситас Ромбольд. В конце октября 2016 года у пары родился сын — Антон Брюль." where id = 242467; 
 update persons  set biography = "Полное имя Томас Влашиха (Thomas Wlaschiha)." where id = 51623; 
 update persons  set biography = "Муж, Георгий Михайлович Турылёв был известным художником-постановщиком киностудии Мосфильм." where id = 1290076; 
 update persons  set biography = "Её дочь – актриса Антонелла Интерленьи." where id = 182208; 
 update persons  set biography = "У актёра три дочери, старшие из которых актрисы Лоис Уинстон и Джема Уинстон." where id = 3716; 
 update persons  set biography = "У Фрэнсис Томелти есть двое детей от брака со Стингом, сын и дочь - Джозеф Самнер (23.11.76) и Фашия Кэтрин Самнер (17.04.82)." where id = 129309; 
 update persons  set biography = "10 августа 2007 года у Матильды Сенье родился сын Луи." where id = 5655; 
 update persons  set biography = "Есть дочь — Фредерик Нуаре." where id = 105775; 
 update persons  set biography = "У Дайан Лейн есть дочь от первого брака с Кристофером Ламбертом - Элеанор Жасмин Ламберт (05.09.93)." where id = 7938; 
 update persons  set biography = "Изучал драму в «Университете Западного Вашингтона», а затем поступил работать в театр Аннэкс, а также в New City Festival и A.H.A. Theater в Сиэтле." where id = 11825; 
 update persons  set biography = "У Колина Хэнкса и Саманты Брайант двое детей: Оливия Джейн и Шарлотта Брайант Хэнкс." where id = 36995; 
 update persons  set biography = "У Мэри Бет Хёрт есть двое детей от второго брака с Полом Шредером, дочь и сын - Молли Джоанна Шредер (род.1984) и Сэм Шредер (род.1988)." where id = 6802; 
 update persons  set biography = "Тайрон родился глухим от глухих родителей." where id = 568809; 
 update persons  set biography = "Перла – дочь бразильского режиссера Чузи Аней-Жардине и актрисы и продюсера Дженнифер МакДональд." where id = 520135; 
 update persons  set biography = "Джесси Фергюсон — открытый гомосексуал." where id = 396529; 
 update persons  set biography = "Окончила мехмат МГУ с красным дипломом." where id = 1152773; 
 update persons  set biography = "В 1974 году Сокуров защитил диплом историка на историческом факультете Горьковского университета." where id = 37383; 
